const fs = require('fs');
const path = require('path');

const i18nPath = path.join(__dirname, 'src/utils/i18n.js');
let i18nContent = fs.readFileSync(i18nPath, 'utf8');

const additionalTranslations = {
    zh: {
        appTitle: "fix it PLEASE",
        headerSubtitle: "租客工具箱",
        navHome: "首頁",
        navRepair: "維修",
        navVault: "檔案櫃",
        navNotes: "筆記",
        navSettings: "設定",
        homeGreeting: "你需要什麼？",
        installTitle: "取得應用程式",
        installSubtitle: "將 fix it PLEASE 安裝到主畫面",
        getOnPlayStore: "在 Google Play 取得",
        playStoreSubtitle: "下載 Android 應用程式",
        fixSomething: "修理東西",
        fixSomethingDesc: "透過簡訊或電子郵件向房東報告問題。",
        requestHistory: "請求歷史",
        requestHistoryDesc: "追蹤過去請求的狀態。",
        documentVault: "文件保險箱",
        documentVaultDesc: "儲存您的租約、檢查照片和收據。",
        recordNote: "記錄筆記",
        recordNoteDesc: "打字或說話來快速記錄任何事情。",
        whatsTheProblem: "有什麼問題？",
        whereIsTheProblem: "問題出在哪裡？",
        whatNeedsFixing: "什麼需要修理？",
        tapToSelectOneOrMore: "點擊選擇一個或多個",
        pleaseSelectLocationFirst: "請先選擇一個位置。",
        tapToSelect: "點擊選擇",
        whereIsIt: "在哪裡？",
        tapTheLocation: "點擊位置",
        howUrgent: "有多緊急？",
        addPhoto: "添加照片（可選）",
        takePhoto: "拍照",
        remove: "刪除",
        reviewAndSend: "檢查並發送",
        issuePlumbing: "水管設備",
        issueElectrical: "電氣設備",
        issueAppliance: "家電",
        issueHvac: "暖氣/冷氣",
        issuePest: "害蟲",
        issueLock: "鎖/門",
        issueWindow: "窗戶",
        issueWaterDamage: "水損壞",
        issueMold: "發霉",
        issueStructural: "結構",
        issueOther: "其他",
        itemSink: "水槽/面盆",
        itemFaucet: "水龍頭",
        itemFridge: "冰箱",
        itemStoveOven: "爐子/烤箱",
        itemDishwasher: "洗碗機",
        itemGarbageDisposal: "垃圾處理器",
        itemCabinets: "櫥櫃/抽屜",
        itemOutlets: "電源插座",
        itemLights: "燈具/裝置",
        itemToilet: "馬桶",
        itemShowerTub: "淋浴/浴缸",
        itemExhaustFan: "排氣扇",
        itemMirror: "鏡子/玻璃",
        itemDoor: "門/鎖/門把",
        itemWindow: "窗戶/百葉窗/紗窗",
        itemCloset: "壁櫥/衣櫃",
        itemWalls: "牆壁/天花板/油漆",
        itemStairs: "樓梯/扶手",
        itemWasher: "洗衣機",
        itemDryer: "烘衣機",
        itemWaterLeak: "漏水/淹水",
        itemHeater: "暖氣機",
        itemWaterHeater: "熱水器",
        itemPest: "害蟲/老鼠",
        itemRoof: "屋頂/排水槽",
        itemParking: "停車場/車道",
        itemLandscaping: "景觀設計/庭院",
        itemTrash: "垃圾/回收",
        itemExteriorDoor: "外門/大門",
        itemOther: "其他",
        locKitchen: "廚房",
        locBathroom: "浴室",
        locBedroom: "臥室",
        locLivingRoom: "客廳",
        locHallway: "走廊",
        locLaundry: "洗衣房",
        locBasement: "地下室",
        locExterior: "室外/公共區域",
        urgencyLow: "低",
        urgencyNormal: "普通",
        urgencyHigh: "高",
        urgencyEmergency: "緊急",
        summaryIssue: "問題",
        summaryLocation: "位置",
        summaryUrgency: "緊急程度",
        summaryPhoto: "照片",
        summaryAttached: "已附加",
        yourInfo: "您的資訊 (用於請求)",
        yourName: "您的姓名",
        yourAddress: "您的地址",
        yourPhoneOptional: "您的電話 (可選)",
        yourEmailOptional: "您的電子郵件 (可選)",
        wellRemember: "我們會記住這個以供下次使用。",
        whoShouldThisGoTo: "這應該發送給誰？",
        landlordNamePlaceholder: "房東姓名",
        phonePlaceholder: "電話號碼",
        emailPlaceholder: "電子郵件地址",
        sendText: "簡訊",
        sendEmail: "電子郵件",
        back: "返回",
        next: "下一步",
        history: "歷史",
        trackRequests: "追蹤過去請求的狀態。",
        noRequestsYet: "尚未有請求。提交後它們會出現在這裡。",
        unknownDate: "未知日期",
        statusPending: "待處理",
        statusInProgress: "進行中",
        statusResolved: "已解決",
        notes: "筆記",
        recordAnything: "記錄您需要記住的任何事情。",
        newNote: "新增筆記",
        typeOrSpeak: "輸入您的筆記或點擊麥克風說話...",
        stop: "停止",
        speak: "說話",
        saveNote: "儲存筆記",
        noNotesYet: "尚未有筆記。點擊上方的按鈕建立一個。",
        speechNotSupported: "此設備不支援語音識別。",
        documentVaultTitle: "文件保險箱",
        keepFilesOrganized: "保持您的重要文件井然有序且易於存取。",
        leaseContract: "租約/合約",
        walkthroughPhotos: "檢查照片",
        receipts: "收據",
        lettersEmails: "信件/電子郵件",
        imagesVideos: "圖片/影片",
        other: "其他",
        items: "項目",
        backToFolders: "← 返回資料夾",
        uploadFileOrPhoto: "上傳檔案或照片",
        noFilesYet: "尚未有檔案。點擊上方添加。",
        settings: "設定",
        settingsSubtitle: "設定一次您的資訊 — 之後將在維修請求中自動使用。",
        yourInfoSection: "您的資訊",
        yourNameLabel: "您的姓名",
        yourAddressLabel: "您的地址",
        yourPhoneLabel: "您的電話",
        yourEmailLabel: "您的電子郵件",
        landlordSection: "房東/管理員",
        landlordNameLabel: "姓名",
        landlordPhoneLabel: "電話號碼",
        landlordEmailLabel: "電子郵件地址",
        saveSettings: "儲存設定",
        saved: "已儲存",
        languageSection: "Language / 語言",
        appLanguage: "應用程式語言",
        messageLanguage: "維修訊息語言",
        messageLanguageHint: "發送維修請求給房東時使用的語言。",
        langEnglish: "English",
        langSpanish: "Español",
        langChinese: "中文",
        langFrench: "Français",
        langGerman: "Deutsch",
        langArabic: "العربية",
        langHindi: "हिन्दी",
        describeIssue: "描述問題（可選）",
        descriptionPlaceholder: "例如「廚房水龍頭漏水已經 3 天了...」",
        takeNewPhoto: "拍張新照片",
        chooseFromGallery: "從相簿中選擇",
        description: "描述",
        commLog: "通訊記錄",
        sentOn: "發送於",
        at: "位於",
        tenantPro: "租客專業版",
        upgradeToPro: "升級至專業版",
        proBenefits: "高級會員專享福利",
        proPrice: "每月 $1",
        proBenefit1: "無限的文件保險箱儲存空間",
        proBenefit2: "將維修信件匯出為 PDF/圖片",
        proBenefit3: "AI 協助的維修分析",
        proBenefit4: "優先提供法律援助支援",
        subscribeNow: "立即訂閱",
        cancelAnytime: "隨時取消",
        alreadyPro: "您已經是專業版會員",
    },
    fr: {
        appTitle: "fix it PLEASE",
        headerSubtitle: "LA BOÎTE À OUTILS DU LOCATAIRE",
        navHome: "Accueil",
        navRepair: "Réparer",
        navVault: "Dossiers",
        navNotes: "Notes",
        navSettings: "Paramètres",
        homeGreeting: "De quoi avez-vous besoin ?",
        installTitle: "Obtenir l'application",
        installSubtitle: "Installez fix it PLEASE sur votre écran d'accueil",
        getOnPlayStore: "Obtenir sur Google Play",
        playStoreSubtitle: "Téléchargez l'application Android",
        fixSomething: "Réparer quelque chose",
        fixSomethingDesc: "Signalez un problème à votre propriétaire par SMS ou e-mail.",
        requestHistory: "Historique",
        requestHistoryDesc: "Suivez le statut de vos demandes passées.",
        documentVault: "Coffre-fort à documents",
        documentVaultDesc: "Stockez vos baux, photos d'inspection et reçus.",
        recordNote: "Enregistrer une note",
        recordNoteDesc: "Tapez ou parlez pour créer une trace rapide de n'importe quoi.",
        whatsTheProblem: "Quel est le problème ?",
        whereIsTheProblem: "Où se situe le problème ?",
        whatNeedsFixing: "Que faut-il réparer ?",
        tapToSelectOneOrMore: "Touchez pour en sélectionner un(e) ou plusieurs",
        pleaseSelectLocationFirst: "Veuillez d'abord sélectionner un emplacement.",
        tapToSelect: "Touchez pour sélectionner",
        whereIsIt: "Où est-ce ?",
        tapTheLocation: "Touchez l'emplacement",
        howUrgent: "Quel niveau d'urgence ?",
        addPhoto: "Ajouter une photo (facultatif)",
        takePhoto: "Prendre une photo",
        remove: "Retirer",
        reviewAndSend: "Vérifier et envoyer",
        issuePlumbing: "Plomberie",
        issueElectrical: "Électricité",
        issueAppliance: "Électroménager",
        issueHvac: "Chauffage / Climatisation",
        issuePest: "Nuisibles",
        issueLock: "Serrure / Porte",
        issueWindow: "Fenêtre",
        issueWaterDamage: "Dégâts des eaux",
        issueMold: "Moisissure",
        issueStructural: "Structurel",
        issueOther: "Autre",
        itemSink: "Évier / Lavabo",
        itemFaucet: "Robinet",
        itemFridge: "Réfrigérateur",
        itemStoveOven: "Cuisinière / Four",
        itemDishwasher: "Lave-vaisselle",
        itemGarbageDisposal: "Broyeur à déchets",
        itemCabinets: "Armoires / Tiroirs",
        itemOutlets: "Prises électriques",
        itemLights: "Lumières / Luminaires",
        itemToilet: "Toilettes",
        itemShowerTub: "Douche / Baignoire",
        itemExhaustFan: "Ventilateur d'extraction",
        itemMirror: "Miroir / Verre",
        itemDoor: "Porte / Serrure / Poignée",
        itemWindow: "Fenêtre / Stores / Moustiquaire",
        itemCloset: "Placard / Penderie",
        itemWalls: "Murs / Plafond / Peinture",
        itemStairs: "Escaliers / Mains courantes",
        itemWasher: "Lave-linge",
        itemDryer: "Sèche-linge",
        itemWaterLeak: "Fuite d'eau / Inondation",
        itemHeater: "Radiateur",
        itemWaterHeater: "Chauffe-eau",
        itemPest: "Nuisibles / Rongeurs",
        itemRoof: "Toit / Gouttières",
        itemParking: "Parking / Allée",
        itemLandscaping: "Aménagement paysager / Cour",
        itemTrash: "Poubelle / Recyclage",
        itemExteriorDoor: "Porte extérieure / Portail",
        itemOther: "Autre",
        locKitchen: "Cuisine",
        locBathroom: "Salle de bain",
        locBedroom: "Chambre",
        locLivingRoom: "Salon",
        locHallway: "Couloir",
        locLaundry: "Buanderie",
        locBasement: "Sous-sol",
        locExterior: "Extérieur / Parties communes",
        urgencyLow: "Faible",
        urgencyNormal: "Normal",
        urgencyHigh: "Élevée",
        urgencyEmergency: "Urgence",
        summaryIssue: "Problème",
        summaryLocation: "Emplacement",
        summaryUrgency: "Urgence",
        summaryPhoto: "Photo",
        summaryAttached: "Ci-jointe",
        yourInfo: "Vos informations (pour la demande)",
        yourName: "Votre nom",
        yourAddress: "Votre adresse",
        yourPhoneOptional: "Votre téléphone (facultatif)",
        yourEmailOptional: "Votre e-mail (facultatif)",
        wellRemember: "Nous les mémoriserons pour la prochaine fois.",
        whoShouldThisGoTo: "À qui cela doit-il être adressé ?",
        landlordNamePlaceholder: "Nom du propriétaire",
        phonePlaceholder: "Numéro de téléphone",
        emailPlaceholder: "Adresse e-mail",
        sendText: "SMS",
        sendEmail: "E-mail",
        back: "Retour",
        next: "Suivant",
        history: "Historique",
        trackRequests: "Suivez le statut de vos demandes passées.",
        noRequestsYet: "Aucune demande pour l'instant. Elles apparaîtront ici après en avoir soumis une.",
        unknownDate: "Date inconnue",
        statusPending: "En attente",
        statusInProgress: "En cours",
        statusResolved: "Résolu",
        notes: "Notes",
        recordAnything: "Laissez une trace de tout ce dont vous devez vous souvenir.",
        newNote: "Nouvelle note",
        typeOrSpeak: "Tapez votre note ou appuyez sur le micro pour parler...",
        stop: "Arrêter",
        speak: "Parler",
        saveNote: "Enregistrer la note",
        noNotesYet: "Aucune note pour l'instant. Appuyez sur le bouton ci-dessus pour en créer une.",
        speechNotSupported: "La reconnaissance vocale n'est pas prise en charge sur cet appareil.",
        documentVaultTitle: "Coffre-fort à documents",
        keepFilesOrganized: "Gardez vos fichiers importants bien organisés et accessibles.",
        leaseContract: "Bail / Contrat",
        walkthroughPhotos: "Photos d'inspection",
        receipts: "Reçus",
        lettersEmails: "Lettres / E-mails",
        imagesVideos: "Images / Vidéos",
        other: "Autre",
        items: "éléments",
        backToFolders: "← Retour aux dossiers",
        uploadFileOrPhoto: "Télécharger un fichier ou une photo",
        noFilesYet: "Aucun fichier pour le moment. Touchez ci-dessus pour en ajouter.",
        settings: "Paramètres",
        settingsSubtitle: "Configurez vos informations une seule fois — elles seront utilisées automatiquement dans vos demandes de réparation.",
        yourInfoSection: "Vos Informations",
        yourNameLabel: "Votre nom",
        yourAddressLabel: "Votre adresse",
        yourPhoneLabel: "Votre téléphone",
        yourEmailLabel: "Votre e-mail",
        landlordSection: "Propriétaire / Gestionnaire",
        landlordNameLabel: "Nom",
        landlordPhoneLabel: "Numéro de téléphone",
        landlordEmailLabel: "Adresse e-mail",
        saveSettings: "Enregistrer les paramètres",
        saved: "Enregistré",
        languageSection: "Language / Langue",
        appLanguage: "Langue de l'application",
        messageLanguage: "Langue du message de réparation",
        messageLanguageHint: "La langue utilisée pour envoyer les demandes de réparation à votre propriétaire.",
        langEnglish: "English",
        langSpanish: "Español",
        langChinese: "中文",
        langFrench: "Français",
        langGerman: "Deutsch",
        langArabic: "العربية",
        langHindi: "हिन्दी",
        describeIssue: "Décrivez le problème (facultatif)",
        descriptionPlaceholder: "Ex. « Le robinet de la cuisine fuit depuis 3 jours... »",
        takeNewPhoto: "Prendre une nouvelle photo",
        chooseFromGallery: "Choisir depuis la galerie",
        description: "Description",
        commLog: "Journal de communication",
        sentOn: "Envoyé le",
        at: "à",
        tenantPro: "Locataire Pro",
        upgradeToPro: "Passer à la version Pro",
        proBenefits: "Avantages Premium",
        proPrice: "1 $ / mois",
        proBenefit1: "Stockage illimité du Coffre-fort à documents",
        proBenefit2: "Exportation des lettres de réparation en PDF/Image",
        proBenefit3: "Analyse de réparation alimentée par l'IA",
        proBenefit4: "Support prioritaire pour l'Aide Juridique",
        subscribeNow: "S'abonner maintenant",
        cancelAnytime: "Annulation à tout moment",
        alreadyPro: "Vous êtes membre Pro",
    },
    de: {
        appTitle: "fix it PLEASE",
        headerSubtitle: "WERKZEUGKASTEN FÜR MIETER",
        navHome: "Start",
        navRepair: "Reparieren",
        navVault: "Dateien",
        navNotes: "Notizen",
        navSettings: "Einstellungen",
        homeGreeting: "Was benötigen Sie?",
        installTitle: "App herunterladen",
        installSubtitle: "Installieren Sie fix it PLEASE auf Ihrem Startbildschirm",
        getOnPlayStore: "Bei Google Play erhältlich",
        playStoreSubtitle: "Laden Sie die Android-App herunter",
        fixSomething: "Etwas reparieren",
        fixSomethingDesc: "Melden Sie Ihrem Vermieter ein Problem per SMS oder E-Mail.",
        requestHistory: "Verlauf",
        requestHistoryDesc: "Verfolgen Sie den Status Ihrer vergangenen Anfragen.",
        documentVault: "Dokumenten-Tresor",
        documentVaultDesc: "Speichern Sie Ihren Mietvertrag, Inspektionsfotos und Quittungen.",
        recordNote: "Notiz aufnehmen",
        recordNoteDesc: "Tippen oder sprechen Sie, um schnell eine Notiz zu erstellen.",
        whatsTheProblem: "Was ist das Problem?",
        whereIsTheProblem: "Wo ist das Problem?",
        whatNeedsFixing: "Was muss repariert werden?",
        tapToSelectOneOrMore: "Tippen Sie, um eine oder mehrere Optionen auszuwählen",
        pleaseSelectLocationFirst: "Bitte wählen Sie zuerst einen Ort aus.",
        tapToSelect: "Tippen Sie zur Auswahl",
        whereIsIt: "Wo ist es?",
        tapTheLocation: "Tippen Sie auf den Ort",
        howUrgent: "Wie dringend?",
        addPhoto: "Foto hinzufügen (optional)",
        takePhoto: "Foto aufnehmen",
        remove: "Entfernen",
        reviewAndSend: "Überprüfen & Senden",
        issuePlumbing: "Sanitäranlagen",
        issueElectrical: "Elektrik",
        issueAppliance: "Haushaltsgeräte",
        issueHvac: "Heizung / Klima",
        issuePest: "Schädlinge",
        issueLock: "Schloss / Tür",
        issueWindow: "Fenster",
        issueWaterDamage: "Wasserschaden",
        issueMold: "Schimmel",
        issueStructural: "Strukturell",
        issueOther: "Sonstiges",
        itemSink: "Spüle / Waschbecken",
        itemFaucet: "Wasserhahn",
        itemFridge: "Kühlschrank",
        itemStoveOven: "Herd / Ofen",
        itemDishwasher: "Geschirrspüler",
        itemGarbageDisposal: "Müllschlucker",
        itemCabinets: "Schränke / Schubladen",
        itemOutlets: "Steckdosen",
        itemLights: "Lichter / Leuchten",
        itemToilet: "Toilette",
        itemShowerTub: "Dusche / Badewanne",
        itemExhaustFan: "Abluftventilator",
        itemMirror: "Spiegel / Glas",
        itemDoor: "Tür / Schloss / Griff",
        itemWindow: "Fenster / Jalousien / Fliegengitter",
        itemCloset: "Schrank / Garderobe",
        itemWalls: "Wände / Decke / Farbe",
        itemStairs: "Treppen / Handläufe",
        itemWasher: "Waschmaschine",
        itemDryer: "Trockner",
        itemWaterLeak: "Wasserleck / Überschwemmung",
        itemHeater: "Heizung",
        itemWaterHeater: "Warmwasserbereiter",
        itemPest: "Schädlinge / Nagetiere",
        itemRoof: "Dach / Dachrinnen",
        itemParking: "Parkplatz / Einfahrt",
        itemLandscaping: "Landschaftsbau / Garten",
        itemTrash: "Müll / Recycling",
        itemExteriorDoor: "Außentür / Tor",
        itemOther: "Sonstiges",
        locKitchen: "Küche",
        locBathroom: "Badezimmer",
        locBedroom: "Schlafzimmer",
        locLivingRoom: "Wohnzimmer",
        locHallway: "Flur",
        locLaundry: "Waschküche",
        locBasement: "Keller",
        locExterior: "Außen / Gemeinschaftsbereich",
        urgencyLow: "Niedrig",
        urgencyNormal: "Normal",
        urgencyHigh: "Hoch",
        urgencyEmergency: "Notfall",
        summaryIssue: "Problem",
        summaryLocation: "Ort",
        summaryUrgency: "Dringlichkeit",
        summaryPhoto: "Foto",
        summaryAttached: "Angehängt",
        yourInfo: "Ihre Informationen (für die Anfrage)",
        yourName: "Ihr Name",
        yourAddress: "Ihre Adresse",
        yourPhoneOptional: "Ihre Telefonnummer (optional)",
        yourEmailOptional: "Ihre E-Mail (optional)",
        wellRemember: "Wir merken uns das fürs nächste Mal.",
        whoShouldThisGoTo: "An wen soll das gehen?",
        landlordNamePlaceholder: "Name des Vermieters",
        phonePlaceholder: "Telefonnummer",
        emailPlaceholder: "E-Mail-Adresse",
        sendText: "SMS",
        sendEmail: "E-mail",
        back: "Zurück",
        next: "Weiter",
        history: "Verlauf",
        trackRequests: "Verfolgen Sie den Status Ihrer vergangenen Anfragen.",
        noRequestsYet: "Noch keine Anfragen. Nach dem Einreichen werden sie hier angezeigt.",
        unknownDate: "Unbekanntes Datum",
        statusPending: "Ausstehend",
        statusInProgress: "In Bearbeitung",
        statusResolved: "Erledigt",
        notes: "Notizen",
        recordAnything: "Notieren Sie alles, woran Sie sich erinnern müssen.",
        newNote: "Neue Notiz",
        typeOrSpeak: "Tippen Sie Ihre Notiz ein oder tippen Sie auf das Mikrofon, um zu sprechen...",
        stop: "Stopp",
        speak: "Sprechen",
        saveNote: "Notiz speichern",
        noNotesYet: "Noch keine Notizen vorhanden. Tippen Sie auf die Schaltfläche oben, um eine zu erstellen.",
        speechNotSupported: "Spracherkennung wird auf diesem Gerät nicht unterstützt.",
        documentVaultTitle: "Dokumenten-Tresor",
        keepFilesOrganized: "Halten Sie Ihre wichtigen Dateien stets griffbereit und organisiert.",
        leaseContract: "Mietvertrag",
        walkthroughPhotos: "Inspektionsfotos",
        receipts: "Quittungen",
        lettersEmails: "Briefe / E-Mails",
        imagesVideos: "Bilder / Videos",
        other: "Sonstiges",
        items: "Elemente",
        backToFolders: "← Zurück zu den Ordnern",
        uploadFileOrPhoto: "Datei oder Foto hochladen",
        noFilesYet: "Bisher noch keine Dateien. Tippen Sie oben, um welche hinzuzufügen.",
        settings: "Einstellungen",
        settingsSubtitle: "Richten Sie Ihre Informationen einmal ein — sie werden dann automatisch in Ihren Reparaturanfragen verwendet.",
        yourInfoSection: "Ihre Informationen",
        yourNameLabel: "Ihr Name",
        yourAddressLabel: "Ihre Adresse",
        yourPhoneLabel: "Ihre Telefonnummer",
        yourEmailLabel: "Ihre E-Mail",
        landlordSection: "Vermieter / Verwalter",
        landlordNameLabel: "Name",
        landlordPhoneLabel: "Telefonnummer",
        landlordEmailLabel: "E-Mail-Adresse",
        saveSettings: "Einstellungen speichern",
        saved: "Gespeichert",
        languageSection: "Language / Sprache",
        appLanguage: "App-Sprache",
        messageLanguage: "Sprache der Reparaturnachricht",
        messageLanguageHint: "Die Sprache, die verwendet wird, wenn Reparaturanfragen an Ihren Vermieter gesendet werden.",
        langEnglish: "English",
        langSpanish: "Español",
        langChinese: "中文",
        langFrench: "Français",
        langGerman: "Deutsch",
        langArabic: "العربية",
        langHindi: "हिन्दी",
        describeIssue: "Beschreiben Sie das Problem (optional)",
        descriptionPlaceholder: "Z.B. „Der Küchenhahn tropft seit 3 Tagen...“",
        takeNewPhoto: "Neues Foto aufnehmen",
        chooseFromGallery: "Aus Galerie wählen",
        description: "Beschreibung",
        commLog: "Kommunikationsprotokoll",
        sentOn: "Gesendet am",
        at: "um",
        tenantPro: "Mieter Pro",
        upgradeToPro: "Auf Pro upgraden",
        proBenefits: "Premium-Vorteile",
        proPrice: "1 $ / Monat",
        proBenefit1: "Unbegrenzter Dokumenten-Tresor-Speicher",
        proBenefit2: "Exportieren von Reparaturbriefen als PDF/Bild",
        proBenefit3: "KI-gestützte Reparaturanalyse",
        proBenefit4: "Vorrangige Rechtshilfeunterstützung",
        subscribeNow: "Jetzt abonnieren",
        cancelAnytime: "Jederzeit kündbar",
        alreadyPro: "Sie sind Pro-Mitglied",
    },
    ar: {
        appTitle: "fix it PLEASE",
        headerSubtitle: "أدوات المستأجر",
        navHome: "الرئيسية",
        navRepair: "إصلاح",
        navVault: "الملفات",
        navNotes: "ملاحظات",
        navSettings: "الإعدادات",
        homeGreeting: "ماذا تحتاج؟",
        installTitle: "احصل على التطبيق",
        installSubtitle: "قم بتثبيت fix it PLEASE على شاشتك الرئيسية",
        getOnPlayStore: "احصل عليه من Google Play",
        playStoreSubtitle: "تنزيل تطبيق أندرويد",
        fixSomething: "إصلاح شيء ما",
        fixSomethingDesc: "أبلغ مالك العقار عن مشكلة عبر رسالة نصية أو بريد إلكتروني.",
        requestHistory: "السجل",
        requestHistoryDesc: "تتبع حالة طلباتك السابقة.",
        documentVault: "خزنة المستندات",
        documentVaultDesc: "قم بتخزين عقد الإيجار وصور وفحص العقار والإيصالات.",
        recordNote: "تسجيل ملاحظة",
        recordNoteDesc: "اكتب أو تحدث لإنشاء سجل سريع لأي شيء.",
        whatsTheProblem: "ما هي المشكلة؟",
        whereIsTheProblem: "أين المشكلة؟",
        whatNeedsFixing: "ما الذي يحتاج إلى إصلاح؟",
        tapToSelectOneOrMore: "انقر لتحديد واحد أو أكثر",
        pleaseSelectLocationFirst: "الرجاء تحديد موقع أولاً.",
        tapToSelect: "انقر للتحديد",
        whereIsIt: "أين؟",
        tapTheLocation: "انقر على الموقع",
        howUrgent: "ما مدى الأهمية العاجلة؟",
        addPhoto: "أضف صورة (اختياري)",
        takePhoto: "التقط صورة",
        remove: "إزالة",
        reviewAndSend: "مراجعة وإرسال",
        issuePlumbing: "سباكة",
        issueElectrical: "كهرباء",
        issueAppliance: "أجهزة",
        issueHvac: "تدفئة / تبريد",
        issuePest: "آفات / حشرات",
        issueLock: "قفل / باب",
        issueWindow: "نافذة",
        issueWaterDamage: "تلف بسبب المياه",
        issueMold: "عفن",
        issueStructural: "هيكلي",
        issueOther: "أخرى",
        itemSink: "حوض/مغسلة",
        itemFaucet: "صنبور",
        itemFridge: "ثلاجة",
        itemStoveOven: "موقد/فرن",
        itemDishwasher: "غسالة صحون",
        itemGarbageDisposal: "جهاز التخلص من النفايات",
        itemCabinets: "خزائن/أدراج",
        itemOutlets: "مآخذ كهربائية",
        itemLights: "مصابيح/إضاءة",
        itemToilet: "مرحاض",
        itemShowerTub: "دش/حوض استحمام",
        itemExhaustFan: "مروحة شفط",
        itemMirror: "مرآة/زجاج",
        itemDoor: "باب/قفل/مقبض",
        itemWindow: "نافذة/ستائر",
        itemCloset: "خزانة ملابس/دولاب",
        itemWalls: "جدران/سقف/طلاء",
        itemStairs: "سلالم/درابزين",
        itemWasher: "غسالة",
        itemDryer: "نشافة",
        itemWaterLeak: "تسرب مياه/فيضان",
        itemHeater: "سخان/مدفأة",
        itemWaterHeater: "سخان مياه",
        itemPest: "آفات/قوارض",
        itemRoof: "سقف/مزاريب",
        itemParking: "موقف سيارات/ممر",
        itemLandscaping: "تنسيق حدائق/فناء",
        itemTrash: "قمامة/إعادة تدوير",
        itemExteriorDoor: "باب خارجي/بوابة",
        itemOther: "أخرى",
        locKitchen: "مطبخ",
        locBathroom: "حمام",
        locBedroom: "غرفة نوم",
        locLivingRoom: "غرفة معيشة",
        locHallway: "ممر",
        locLaundry: "غرفة غسيل",
        locBasement: "قبو",
        locExterior: "الخارج / منطقة مشتركة",
        urgencyLow: "منخفضة",
        urgencyNormal: "عادية",
        urgencyHigh: "عالية",
        urgencyEmergency: "طوارئ",
        summaryIssue: "المشكلة",
        summaryLocation: "الموقع",
        summaryUrgency: "الأهمية العاجلة",
        summaryPhoto: "الصورة",
        summaryAttached: "مرفقة",
        yourInfo: "معلوماتك (للطلب)",
        yourName: "اسمك",
        yourAddress: "عنوانك",
        yourPhoneOptional: "هاتفك (اختياري)",
        yourEmailOptional: "بريدك الإلكتروني (اختياري)",
        wellRemember: "سنتذكر ذلك في المرة القادمة.",
        whoShouldThisGoTo: "إلى من يجب إرسال هذا؟",
        landlordNamePlaceholder: "اسم مالك العقار",
        phonePlaceholder: "رقم الهاتف",
        emailPlaceholder: "عنوان البريد الإلكتروني",
        sendText: "رسالة نصية",
        sendEmail: "بريد إلكتروني",
        back: "الخلف",
        next: "التالي",
        history: "السجل",
        trackRequests: "تتبع حالة طلباتك السابقة.",
        noRequestsYet: "لا توجد طلبات حتى الآن. ستظهر هنا بعد الإرسال.",
        unknownDate: "تاريخ غير معروف",
        statusPending: "قيد الانتظار",
        statusInProgress: "قيد التنفيذ",
        statusResolved: "تم الحل",
        notes: "ملاحظات",
        recordAnything: "سجل أي شيء تحتاج إلى تذكره.",
        newNote: "ملاحظة جديدة",
        typeOrSpeak: "اكتب ملاحظتك أو انقر على الميكروفون للتحدث...",
        stop: "توقف",
        speak: "تحدث",
        saveNote: "حفظ الملاحظة",
        noNotesYet: "لا توجد ملاحظات بعد. انقر على الزر أعلاه لإنشاء واحدة.",
        speechNotSupported: "التعرف على الصوت غير مدعوم على هذا الجهاز.",
        documentVaultTitle: "خزنة المستندات",
        keepFilesOrganized: "حافظ على ملفاتك المهمة منظمة ويمكن الوصول إليها.",
        leaseContract: "عقد الإيجار",
        walkthroughPhotos: "صور الفحص",
        receipts: "الإيصالات",
        lettersEmails: "رسائل / بريد إلكتروني",
        imagesVideos: "صور / فيديو",
        other: "أخرى",
        items: "عناصر",
        backToFolders: "← العودة إلى المجلدات",
        uploadFileOrPhoto: "تحميل ملف أو صورة",
        noFilesYet: "لا توجد ملفات بعد. المس أعلاه للإضافة.",
        settings: "الإعدادات",
        settingsSubtitle: "قم بإعداد معلوماتك مرة واحدة — وسيتم استخدامها تلقائيًا في طلبات الإصلاح الخاصة بك.",
        yourInfoSection: "معلوماتك",
        yourNameLabel: "اسمك",
        yourAddressLabel: "عنوانك",
        yourPhoneLabel: "هاتفك",
        yourEmailLabel: "بريدك الإلكتروني",
        landlordSection: "مالك العقار / المدير",
        landlordNameLabel: "الاسم",
        landlordPhoneLabel: "رقم الهاتف",
        landlordEmailLabel: "عنوان البريد الإلكتروني",
        saveSettings: "حفظ الإعدادات",
        saved: "تم الحفظ",
        languageSection: "Language / اللغة",
        appLanguage: "لغة التطبيق",
        messageLanguage: "لغة رسالة الإصلاح",
        messageLanguageHint: "اللغة المستخدمة عند إرسال طلبات الإصلاح إلى مالك العقار.",
        langEnglish: "English",
        langSpanish: "Español",
        langChinese: "中文",
        langFrench: "Français",
        langGerman: "Deutsch",
        langArabic: "العربية",
        langHindi: "हिन्दी",
        describeIssue: "وصف المشكلة (اختياري)",
        descriptionPlaceholder: "مثلاً: 'حنفية المطبخ تسرب المياه منذ 3 أيام...'",
        takeNewPhoto: "التقط صورة جديدة",
        chooseFromGallery: "اختر من المعرض",
        description: "وصف",
        commLog: "سجل الاتصالات",
        sentOn: "تم الإرسال في",
        at: "في",
        tenantPro: "برو للمستأجر",
        upgradeToPro: "الترقية للنسخة برو",
        proBenefits: "مزايا الإصدار الاستثنائي",
        proPrice: "١ دولار / للشهر",
        proBenefit1: "سعة غير محدودة لخزنة المستندات",
        proBenefit2: "تصدير رسائل طلبات الإصلاح بصيغة PDF/صورة",
        proBenefit3: "تحليل عمليات الإصلاح المدعوم بالذكاء الاصطناعي",
        proBenefit4: "دعم مخصص ذو أولوية للمساعدة القانونية",
        subscribeNow: "اشترك الآن",
        cancelAnytime: "إمكانية الإلغاء في أي وقت",
        alreadyPro: "أنت عضو من فئة برو",
    },
    hi: {
        appTitle: "fix it PLEASE",
        headerSubtitle: "किरायेदार का टूलबॉक्स",
        navHome: "होम",
        navRepair: "मरम्मत",
        navVault: "फ़ाइलें",
        navNotes: "नोट्स",
        navSettings: "सेटिंग्स",
        homeGreeting: "आपको क्या चाहिए?",
        installTitle: "ऐप प्राप्त करें",
        installSubtitle: "अपनी होम स्क्रीन पर fix it PLEASE इंस्टॉल करें",
        getOnPlayStore: "Google Play पर प्राप्त करें",
        playStoreSubtitle: "एंड्रॉइड ऐप डाउनलोड करें",
        fixSomething: "कुछ ठीक करें",
        fixSomethingDesc: "अपने मकान मालिक को टेक्स्ट या ईमेल के माध्यम से समस्या की रिपोर्ट करें।",
        requestHistory: "इतिहास",
        requestHistoryDesc: "अपने पिछले अनुरोधों की स्थिति ट्रैक करें।",
        documentVault: "दस्तावेज़ तिजोरी",
        documentVaultDesc: "अपना पट्टा, वॉकथ्रू तस्वीरें और रसीदें स्टोर करें।",
        recordNote: "नोट रिकॉर्ड करें",
        recordNoteDesc: "किसी भी चीज़ का त्वरित रिकॉर्ड बनाने के लिए टाइप करें या बोलें।",
        whatsTheProblem: "क्या समस्या है?",
        whereIsTheProblem: "समस्या कहाँ है?",
        whatNeedsFixing: "क्या ठीक करने की आवश्यकता है?",
        tapToSelectOneOrMore: "एक या अधिक चुनने के लिए टैप करें",
        pleaseSelectLocationFirst: "कृपया पहले एक स्थान चुनें।",
        tapToSelect: "चुनने के लिए टैप करें",
        whereIsIt: "यह कहाँ है?",
        tapTheLocation: "स्थान टैप करें",
        howUrgent: "कितना जरूरी है?",
        addPhoto: "एक तस्वीर जोड़ें (वैकल्पिक)",
        takePhoto: "तस्वीर लें",
        remove: "हटाएं",
        reviewAndSend: "समीक्षा करें और भेजें",
        issuePlumbing: "प्लंबिंग",
        issueElectrical: "विद्युत",
        issueAppliance: "उपकरण",
        issueHvac: "हीट/एसी",
        issuePest: "कीट",
        issueLock: "ताला/दरवाजा",
        issueWindow: "खिड़की",
        issueWaterDamage: "पानी से नुकसान",
        issueMold: "फफूंद",
        issueStructural: "संरचनात्मक",
        issueOther: "अन्य",
        itemSink: "सिंक / बेसिन",
        itemFaucet: "नल",
        itemFridge: "फ्रिज / रेफ्रिजरेटर",
        itemStoveOven: "स्टोव / ओवन",
        itemDishwasher: "डिशवॉशर",
        itemGarbageDisposal: "कचरा निपटान",
        itemCabinets: "कैबिनेट / दराज",
        itemOutlets: "इलेक्ट्रिकल आउटलेट / सॉकेट",
        itemLights: "लाइट / फिक्स्चर",
        itemToilet: "शौचालय / कमोड",
        itemShowerTub: "शावर / बाथटब",
        itemExhaustFan: "एग्जॉस्ट फैन",
        itemMirror: "दर्पण / कांच",
        itemDoor: "दरवाजा / ताला / हैंडल",
        itemWindow: "खिड़की / ब्लाइंड्स / स्क्रीन",
        itemCloset: "अलमारी / कोठरी",
        itemWalls: "दीवारें / छत / पेंट",
        itemStairs: "सीढ़ियाँ / रेलिंग",
        itemWasher: "वॉशर / कपड़े धोने की मशीन",
        itemDryer: "ड्रायर",
        itemWaterLeak: "पानी का रिसाव / बाढ़",
        itemHeater: "हीटर",
        itemWaterHeater: "वाटर हीटर / गीजर",
        itemPest: "कीड़े / चूहे",
        itemRoof: "छत / गटर",
        itemParking: "पार्किंग / ड्राइववे",
        itemLandscaping: "लैंडस्केपिंग / यार्ड",
        itemTrash: "कचरा / रीसाइक्लिंग",
        itemExteriorDoor: "बाहरी दरवाजा / गेट",
        itemOther: "अन्य",
        locKitchen: "बसोई घर",
        locBathroom: "शौचालय/स्नानघर",
        locBedroom: "बेडरूम",
        locLivingRoom: "लिविंग रूम",
        locHallway: "हॉल",
        locLaundry: "लॉन्ड्री",
        locBasement: "तहखाना",
        locExterior: "बाहर/साझा क्षेत्र",
        urgencyLow: "कम",
        urgencyNormal: "सामान्य",
        urgencyHigh: "उच्च",
        urgencyEmergency: "आपातकालीन",
        summaryIssue: "समस्या",
        summaryLocation: "स्थान",
        summaryUrgency: "ज़रूरीपन",
        summaryPhoto: "तस्वीर",
        summaryAttached: "संलग्न",
        yourInfo: "आपकी जानकारी (अनुरोध के लिए)",
        yourName: "आपका नाम",
        yourAddress: "आपका पता",
        yourPhoneOptional: "आपका फोन (वैकल्पिक)",
        yourEmailOptional: "आपका ईमेल (वैकल्पिक)",
        wellRemember: "हम अगली बार के लिए यह याद रखेंगे।",
        whoShouldThisGoTo: "यह किसे जाना चाहिए?",
        landlordNamePlaceholder: "मकान मालिक का नाम",
        phonePlaceholder: "फ़ोन नंबर",
        emailPlaceholder: "ईमेल पता",
        sendText: "टेक्स्ट",
        sendEmail: "ईमेल",
        back: "पीछे",
        next: "आगे",
        history: "इतिहास",
        trackRequests: "अपने पिछले अनुरोधों की स्थिति ट्रैक करें।",
        noRequestsYet: "अभी तक कोई अनुरोध नहीं। सबमिट करने के बाद वे यहाँ दिखाई देंगे।",
        unknownDate: "अज्ञात दिनांक",
        statusPending: "लंबित",
        statusInProgress: "प्रगतिरत",
        statusResolved: "समाधान किया गया",
        notes: "नोट्स",
        recordAnything: "कुछ भी रिकॉर्ड करें जिसे आपको याद रखने की आवश्यकता हो।",
        newNote: "नया नोट",
        typeOrSpeak: "अपना नोट टाइप करें या बोलने के लिए माइक टैप करें...",
        stop: "रुकें",
        speak: "बोलें",
        saveNote: "नोट सहेजें",
        noNotesYet: "अभी तक कोई नोट नहीं। एक बनाने के लिए ऊपर दिए गए बटन को टैप करें।",
        speechNotSupported: "इस डिवाइस पर वाक् पहचान समर्थित नहीं है।",
        documentVaultTitle: "दस्तावेज़ तिजोरी",
        keepFilesOrganized: "अपनी महत्वपूर्ण फ़ाइलों को व्यवस्थित और सुलभ रखें।",
        leaseContract: "पट्टा / अनुबंध",
        walkthroughPhotos: "वॉकथ्रू तस्वीरें",
        receipts: "रसीदें",
        lettersEmails: "पत्र / ईमेल",
        imagesVideos: "छवियां / वीडियो",
        other: "अन्य",
        items: "आइटम",
        backToFolders: "← फोल्डर्स पर वापस लौटें",
        uploadFileOrPhoto: "फ़ाइल या फोटो अपलोड करें",
        noFilesYet: "अभी कोई फ़ाइलें नहीं। जोड़ने के लिए ऊपर टैप करें।",
        settings: "सेटिंग्स",
        settingsSubtitle: "अपनी जानकारी एक बार सेट करें — यह स्वचालित रूप से आपके मरम्मत अनुरोधों में उपयोग की जाएगी।",
        yourInfoSection: "आपकी जानकारी",
        yourNameLabel: "आपका नाम",
        yourAddressLabel: "आपका पता",
        yourPhoneLabel: "आपका फोन",
        yourEmailLabel: "आपका ईमेल",
        landlordSection: "मकान मालिक / प्रबंधक",
        landlordNameLabel: "नाम",
        landlordPhoneLabel: "फ़ोन नंबर",
        landlordEmailLabel: "ईमेल पता",
        saveSettings: "सेटिंग्स सहेजें",
        saved: "सहेजा गया",
        languageSection: "Language / भाषा",
        appLanguage: "ऐप की भाषा",
        messageLanguage: "मरम्मत संदेश की भाषा",
        messageLanguageHint: "अपने मकान मालिक को मरम्मत का अनुरोध भेजते समय इस्तेमाल की जाने वाली भाषा।",
        langEnglish: "English",
        langSpanish: "Español",
        langChinese: "中文",
        langFrench: "Français",
        langGerman: "Deutsch",
        langArabic: "العربية",
        langHindi: "हिन्दी",
        describeIssue: "समस्या का वर्णन करें (वैकल्पिक)",
        descriptionPlaceholder: "उदाहरण: 'रसोई का नल ३ दिनों से रिस रहा है...'",
        takeNewPhoto: "नई तस्वीर लें",
        chooseFromGallery: "गैलरी से चुनें",
        description: "विवरण",
        commLog: "संचार लॉग",
        sentOn: "भेजा गया",
        at: "समय",
        tenantPro: "किरायेदार प्रो",
        upgradeToPro: "प्रो में अपग्रेड करें",
        proBenefits: "प्रीमियम लाभ",
        proPrice: "$1 / महीना",
        proBenefit1: "असीमित दस्तावेज़ तिजोरी भंडारण",
        proBenefit2: "मरम्मत पत्रों को पीडीएफ/छवि के रूप में निर्यात करें",
        proBenefit3: "एआई-संचालित मरम्मत विश्लेषण",
        proBenefit4: "प्राथमिकता कानूनी सहायता समर्थन",
        subscribeNow: "अभी सदस्यता लें",
        cancelAnytime: "किसी भी समय रद्द करें",
        alreadyPro: "आप प्रो सदस्य हैं",
    }
};

const additionalMessageTranslations = {
    zh: {
        maintenanceRequest: "維修請求",
        to: "致",
        from: "來自",
        address: "地址",
        contactPhone: "聯絡電話",
        contactEmail: "聯絡電子郵件",
        issue: "問題",
        location: "位置",
        urgency: "緊急程度",
        attachInstructionIos: "[!] 請點擊 + 或附檔圖示以新增您剛剛從照片/相機膠卷所拍攝的照片。",
        attachInstructionAndroid: "[!] 請點擊 + 或附檔圖示以新增您剛剛從相簿所拍攝的照片。",
        attachInstructionWeb: "[!] 傳送前，請先從您的檔案中手動附加照片。",
        emailSubject: "維修請求",
        issuePlumbing: "水管設備",
        issueElectrical: "電氣設備",
        issueAppliance: "家電",
        issueHvac: "暖氣/冷氣",
        issuePest: "害蟲",
        issueLock: "鎖/門",
        issueWindow: "窗戶",
        issueWaterDamage: "水損壞",
        issueMold: "發霉",
        issueStructural: "結構",
        issueOther: "其他",
        itemSink: "水槽/面盆",
        itemFaucet: "水龍頭",
        itemFridge: "冰箱",
        itemStoveOven: "爐子/烤箱",
        itemDishwasher: "洗碗機",
        itemGarbageDisposal: "垃圾處理器",
        itemCabinets: "櫥櫃/抽屜",
        itemOutlets: "電源插座",
        itemLights: "燈具/裝置",
        itemToilet: "馬桶",
        itemShowerTub: "淋浴/浴缸",
        itemExhaustFan: "排氣扇",
        itemMirror: "鏡子/玻璃",
        itemDoor: "門/鎖/門把",
        itemWindow: "窗戶/百葉窗/紗窗",
        itemCloset: "壁櫥/衣櫃",
        itemWalls: "牆壁/天花板/油漆",
        itemStairs: "樓梯/扶手",
        itemWasher: "洗衣機",
        itemDryer: "烘衣機",
        itemWaterLeak: "漏水/淹水",
        itemHeater: "暖氣機",
        itemWaterHeater: "熱水器",
        itemPest: "害蟲/老鼠",
        itemRoof: "屋頂/排水槽",
        itemParking: "停車場/車道",
        itemLandscaping: "景觀設計/庭院",
        itemTrash: "垃圾/回收",
        itemExteriorDoor: "外門/大門",
        itemOther: "其他",
        locKitchen: "廚房",
        locBathroom: "浴室",
        locBedroom: "臥室",
        locLivingRoom: "客廳",
        locHallway: "走廊",
        locLaundry: "洗衣房",
        locBasement: "地下室",
        locExterior: "室外/公共區域",
        urgencyLow: "低",
        urgencyNormal: "普通",
        urgencyHigh: "高",
        urgencyEmergency: "緊急",
    },
    fr: {
        maintenanceRequest: "Demande de Réparation",
        to: "Pour",
        from: "De",
        address: "Adresse",
        contactPhone: "Téléphone de Contact",
        contactEmail: "E-mail de Contact",
        issue: "Problème",
        location: "Emplacement",
        urgency: "Urgence",
        attachInstructionIos: "[!] Veuillez appuyer sur le + ou l'icône de pièce jointe pour ajouter la photo que vous venez de prendre depuis vos Photos/Pellicule.",
        attachInstructionAndroid: "[!] Veuillez appuyer sur le + ou l'icône de pièce jointe pour ajouter la photo que vous venez de prendre depuis votre Galerie.",
        attachInstructionWeb: "[!] Veuillez joindre manuellement la photo depuis vos fichiers avant de l'envoyer.",
        emailSubject: "Demande de Réparation",
        issuePlumbing: "Plomberie",
        issueElectrical: "Électricité",
        issueAppliance: "Électroménager",
        issueHvac: "Chauffage / Climatisation",
        issuePest: "Nuisibles",
        issueLock: "Serrure / Porte",
        issueWindow: "Fenêtre",
        issueWaterDamage: "Dégâts des eaux",
        issueMold: "Moisissure",
        issueStructural: "Structurel",
        issueOther: "Autre",
        itemSink: "Évier / Lavabo",
        itemFaucet: "Robinet",
        itemFridge: "Réfrigérateur",
        itemStoveOven: "Cuisinière / Four",
        itemDishwasher: "Lave-vaisselle",
        itemGarbageDisposal: "Broyeur à déchets",
        itemCabinets: "Armoires / Tiroirs",
        itemOutlets: "Prises électriques",
        itemLights: "Lumières / Luminaires",
        itemToilet: "Toilettes",
        itemShowerTub: "Douche / Baignoire",
        itemExhaustFan: "Ventilateur d'extraction",
        itemMirror: "Miroir / Verre",
        itemDoor: "Porte / Serrure / Poignée",
        itemWindow: "Fenêtre / Stores / Moustiquaire",
        itemCloset: "Placard / Penderie",
        itemWalls: "Murs / Plafond / Peinture",
        itemStairs: "Escaliers / Mains courantes",
        itemWasher: "Lave-linge",
        itemDryer: "Sèche-linge",
        itemWaterLeak: "Fuite d'eau / Inondation",
        itemHeater: "Radiateur",
        itemWaterHeater: "Chauffe-eau",
        itemPest: "Nuisibles / Rongeurs",
        itemRoof: "Toit / Gouttières",
        itemParking: "Parking / Allée",
        itemLandscaping: "Aménagement paysager / Cour",
        itemTrash: "Poubelle / Recyclage",
        itemExteriorDoor: "Porte extérieure / Portail",
        itemOther: "Autre",
        locKitchen: "Cuisine",
        locBathroom: "Salle de bain",
        locBedroom: "Chambre",
        locLivingRoom: "Salon",
        locHallway: "Couloir",
        locLaundry: "Buanderie",
        locBasement: "Sous-sol",
        locExterior: "Extérieur / Parties communes",
        urgencyLow: "FAIBLE",
        urgencyNormal: "NORMAL",
        urgencyHigh: "ÉLEVÉE",
        urgencyEmergency: "URGENCE",
    },
    de: {
        maintenanceRequest: "Reparaturanfrage",
        to: "An",
        from: "Von",
        address: "Adresse",
        contactPhone: "Kontakt-Telefon",
        contactEmail: "Kontakt-E-Mail",
        issue: "Problem",
        location: "Ort",
        urgency: "Dringlichkeit",
        attachInstructionIos: "[!] Bitte tippen Sie auf das +  oder das Anhangssymbol, um das gerade gemachte Foto aus Ihren Fotos/Aufnahmen hinzuzufügen.",
        attachInstructionAndroid: "[!] Bitte tippen Sie auf das + oder das Anhangssymbol, um das gerade aufgenommene Foto aus Ihrer Galerie hinzuzufügen.",
        attachInstructionWeb: "[!] Bitte fügen Sie das Foto aus Ihren Dateien vor dem Senden manuell an.",
        emailSubject: "Reparaturanfrage",
        issuePlumbing: "Sanitäranlagen",
        issueElectrical: "Elektrik",
        issueAppliance: "Haushaltsgeräte",
        issueHvac: "Heizung / Klima",
        issuePest: "Schädlinge",
        issueLock: "Schloss / Tür",
        issueWindow: "Fenster",
        issueWaterDamage: "Wasserschaden",
        issueMold: "Schimmel",
        issueStructural: "Strukturell",
        issueOther: "Sonstiges",
        itemSink: "Spüle / Waschbecken",
        itemFaucet: "Wasserhahn",
        itemFridge: "Kühlschrank",
        itemStoveOven: "Herd / Ofen",
        itemDishwasher: "Geschirrspüler",
        itemGarbageDisposal: "Müllschlucker",
        itemCabinets: "Schränke / Schubladen",
        itemOutlets: "Steckdosen",
        itemLights: "Lichter / Leuchten",
        itemToilet: "Toilette",
        itemShowerTub: "Dusche / Badewanne",
        itemExhaustFan: "Abluftventilator",
        itemMirror: "Spiegel / Glas",
        itemDoor: "Tür / Schloss / Griff",
        itemWindow: "Fenster / Jalousien / Fliegengitter",
        itemCloset: "Schrank / Garderobe",
        itemWalls: "Wände / Decke / Farbe",
        itemStairs: "Treppen / Handläufe",
        itemWasher: "Waschmaschine",
        itemDryer: "Trockner",
        itemWaterLeak: "Wasserleck / Überschwemmung",
        itemHeater: "Heizung",
        itemWaterHeater: "Warmwasserbereiter",
        itemPest: "Schädlinge / Nagetiere",
        itemRoof: "Dach / Dachrinnen",
        itemParking: "Parkplatz / Einfahrt",
        itemLandscaping: "Landschaftsbau / Garten",
        itemTrash: "Müll / Recycling",
        itemExteriorDoor: "Außentür / Tor",
        itemOther: "Sonstiges",
        locKitchen: "Küche",
        locBathroom: "Badezimmer",
        locBedroom: "Schlafzimmer",
        locLivingRoom: "Wohnzimmer",
        locHallway: "Flur",
        locLaundry: "Waschküche",
        locBasement: "Keller",
        locExterior: "Außen / Gemeinschaftsbereich",
        urgencyLow: "NIEDRIG",
        urgencyNormal: "NORMAL",
        urgencyHigh: "HOCH",
        urgencyEmergency: "NOTFALL",
    },
    ar: {
        maintenanceRequest: "طلب صيانة",
        to: "إلى",
        from: "من",
        address: "العنوان",
        contactPhone: "هاتف الاتصال",
        contactEmail: "البريد الإلكتروني للاتصال",
        issue: "المشكلة",
        location: "الموقع",
        urgency: "الأهمية العاجلة",
        attachInstructionIos: "[!] الرجاء النقر على رمز + أو الإرفاق لإضافة الصورة التي التقطتها للتو من الصور/ألبوم الكاميرا.",
        attachInstructionAndroid: "[!] الرجاء النقر على أيقونة + أو الرفاق لإضافة الصورة التي التقطتها للتو من معرض الصور.",
        attachInstructionWeb: "[!] الرجاء إرفاق الصورة يدويًا من ملفاتك قبل الإرسال.",
        emailSubject: "طلب صيانة",
        issuePlumbing: "سباكة",
        issueElectrical: "كهرباء",
        issueAppliance: "أجهزة",
        issueHvac: "تدفئة / تبريد",
        issuePest: "آفات / حشرات",
        issueLock: "قفل / باب",
        issueWindow: "نافذة",
        issueWaterDamage: "تلف بسبب المياه",
        issueMold: "عفن",
        issueStructural: "هيكلي",
        issueOther: "أخرى",
        itemSink: "حوض/مغسلة",
        itemFaucet: "صنبور",
        itemFridge: "ثلاجة",
        itemStoveOven: "موقد/فرن",
        itemDishwasher: "غسالة صحون",
        itemGarbageDisposal: "جهاز التخلص من النفايات",
        itemCabinets: "خزائن/أدراج",
        itemOutlets: "مآخذ كهربائية",
        itemLights: "مصابيح/إضاءة",
        itemToilet: "مرحاض",
        itemShowerTub: "دش/حوض استحمام",
        itemExhaustFan: "مروحة شفط",
        itemMirror: "مرآة/زجاج",
        itemDoor: "باب/قفل/مقبض",
        itemWindow: "نافذة/ستائر",
        itemCloset: "خزانة ملابس/دولاب",
        itemWalls: "جدران/سقف/طلاء",
        itemStairs: "سلالم/درابزين",
        itemWasher: "غسالة",
        itemDryer: "نشافة",
        itemWaterLeak: "تسرب مياه/فيضان",
        itemHeater: "سخان/مدفأة",
        itemWaterHeater: "سخان مياه",
        itemPest: "آفات/قوارض",
        itemRoof: "سقف/مزاريب",
        itemParking: "موقف سيارات/ممر",
        itemLandscaping: "تنسيق حدائق/فناء",
        itemTrash: "قمامة/إعادة تدوير",
        itemExteriorDoor: "باب خارجي/بوابة",
        itemOther: "أخرى",
        locKitchen: "مطبخ",
        locBathroom: "حمام",
        locBedroom: "غرفة نوم",
        locLivingRoom: "غرفة معيشة",
        locHallway: "ممر",
        locLaundry: "غرفة غسيل",
        locBasement: "قبو",
        locExterior: "الخارج / منطقة مشتركة",
        urgencyLow: "منخفضة",
        urgencyNormal: "عادية",
        urgencyHigh: "عالية",
        urgencyEmergency: "طوارئ",
    },
    hi: {
        maintenanceRequest: "अनुरक्षण निवेदन",
        to: "के लिए",
        from: "की ओर से",
        address: "पता",
        contactPhone: "सम्पर्क फोन",
        contactEmail: "सम्पर्क ईमेल",
        issue: "समस्या",
        location: "स्थान",
        urgency: "ज़रूरीपन",
        attachInstructionIos: "[!] कृपया अपने फ़ोटो/कैमरा रोल से अभी-अभी ली गई फ़ोटो जोड़ने के लिए + या अटैच आइकन टैप करें।",
        attachInstructionAndroid: "[!] कृपया अपनी गैलरी से अभी-अभी ली गई फ़ोटो जोड़ने के लिए + या अटैच आइकन टैप करें।",
        attachInstructionWeb: "[!] कृपया भेजने से पहले अपनी फ़ाइलों से फ़ोटो मैन्युअल रूप से संलग्न करें।",
        emailSubject: "अनुरक्षण अनुरोध",
        issuePlumbing: "प्लंबिंग",
        issueElectrical: "विद्युत",
        issueAppliance: "उपकरण",
        issueHvac: "हीट/एसी",
        issuePest: "कीट",
        issueLock: "ताला/दरवाजा",
        issueWindow: "खिड़की",
        issueWaterDamage: "पानी से नुकसान",
        issueMold: "फफूंद",
        issueStructural: "संरचनात्मक",
        issueOther: "अन्य",
        itemSink: "सिंक / बेसिन",
        itemFaucet: "नल",
        itemFridge: "फ्रिज / रेफ्रिजरेटर",
        itemStoveOven: "स्टोव / ओवन",
        itemDishwasher: "डिशवॉशर",
        itemGarbageDisposal: "कचरा निपटान",
        itemCabinets: "कैबिनेट / दराज",
        itemOutlets: "इलेक्ट्रिकल आउटलेट / सॉकेट",
        itemLights: "लाइट / फिक्स्चर",
        itemToilet: "शौचालय / कमोड",
        itemShowerTub: "शावर / बाथटब",
        itemExhaustFan: "एग्जॉस्ट फैन",
        itemMirror: "दर्पण / कांच",
        itemDoor: "दरवाजा / ताला / हैंडल",
        itemWindow: "खिड़की / ब्लाइंड्स / स्क्रीन",
        itemCloset: "अलमारी / कोठरी",
        itemWalls: "दीवारें / छत / पेंट",
        itemStairs: "सीढ़ियाँ / रेलिंग",
        itemWasher: "वॉशर / कपड़े धोने की मशीन",
        itemDryer: "ड्रायर",
        itemWaterLeak: "पानी का रिसाव / बाढ़",
        itemHeater: "हीटर",
        itemWaterHeater: "वाटर हीटर / गीजर",
        itemPest: "कीड़े / चूहे",
        itemRoof: "छत / गटर",
        itemParking: "पार्किंग / ड्राइववे",
        itemLandscaping: "लैंडस्केपिंग / यार्ड",
        itemTrash: "कचरा / रीसाइक्लिंग",
        itemExteriorDoor: "बाहरी दरवाजा / गेट",
        itemOther: "अन्य",
        locKitchen: "बसोई घर",
        locBathroom: "शौचालय/स्नानघर",
        locBedroom: "बेडरूम",
        locLivingRoom: "लिविंग रूम",
        locHallway: "हॉल",
        locLaundry: "लॉन्ड्री",
        locBasement: "तहखाना",
        locExterior: "बाहर/साझा क्षेत्र",
        urgencyLow: "कम",
        urgencyNormal: "सामान्य",
        urgencyHigh: "उच्च",
        urgencyEmergency: "आपातकालीन",
    }
};

const tMatch = i18nContent.match(/const translations = \{[\s\S]+?\n\};\n\n\/\/ Message-only translations/m);
if (tMatch) {
    let innerTranslators = tMatch[0].replace(/\n\};\n\n\/\/ Message-only translations/m, '');
    for (const [lang, obj] of Object.entries(additionalTranslations)) {
        innerTranslators += `,\n  ${lang}: ${JSON.stringify(obj, null, 4)}`;
    }
    innerTranslators += `\n};\n\n// Message-only translations`;
    i18nContent = i18nContent.replace(tMatch[0], innerTranslators);
}

const mtMatch = i18nContent.match(/const messageTranslations = \{[\s\S]+?\n\};\n\n\/\/ Map issue IDs/m);
if (mtMatch) {
    let innerTranslators = mtMatch[0].replace(/\n\};\n\n\/\/ Map issue IDs/m, '');
    for (const [lang, obj] of Object.entries(additionalMessageTranslations)) {
        innerTranslators += `,\n  ${lang}: ${JSON.stringify(obj, null, 4)}`;
    }
    innerTranslators += `\n};\n\n// Map issue IDs`;
    i18nContent = i18nContent.replace(mtMatch[0], innerTranslators);
}

fs.writeFileSync(i18nPath, i18nContent);
console.log('Done mapping.');
